### ISSUE TITLE
On-prem Goobi and Preservica decommissioning

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4187]
### Objective

Sustainable digitised and born-digital preservation

### Measures

- Have all on-prem Goobi servers been decommisioned?
- Have all Preservica servers been decommissioned?
- Has all Preservica content been removed from S3?

### Initiatives

- [x] Delete on-prem Goobi storage
- [x] Delete on-prem Preservica storage
- [x] Delete S3 Preservica storage
- [x] Delete on-prem copy of METS and ALTO (#4189)
- [x] Delete temporary S3 copy of METS and ALTO (#4215, #4240, #4241, #4316)
- [x] Clean up the remaining files in the DDS file share (#4238, #4252, #4256, #4189, #4289)
- [x] Remove legacy space and data in DLCS
- [x] Decommission on-prem Goobi environment
- [x] Decommission on-prem Preservica environment

**Comment by alexwlchan** [comment]
Script to clean up the on-prem copy of the ALTO files, which checks for the presence of an equivalent file (by size and checksum) before deleting:

<details>
<summary>cleanup_alto.py</summary>

```python
#!/usr/bin/env python

import functools
import hashlib
import json
import os
import re
import sys
import termcolor

import tqdm
from wellcome_storage_service import StorageServiceClient


def get_alto_paths(root):
    for dirpath, _, filenames in os.walk(root):
        if not dirpath.endswith("_alto"):
            continue

        for f in filenames:
            if not f.endswith(".xml"):
                continue

            yield (f, os.path.join(dirpath, f))


def get_storage_client(api_url):
    creds_path = os.path.join(
        os.environ["HOME"], ".wellcome-storage", "oauth-credentials.json"
    )
    oauth_creds = json.load(open(creds_path))

    return StorageServiceClient(
        api_url=api_url,
        client_id=oauth_creds["client_id"],
        client_secret=oauth_creds["client_secret"],
        token_url=oauth_creds["token_url"],
    )


@functools.lru_cache()
def get_bag(b_number):
    client = get_storage_client("https://api.wellcomecollection.org/storage/v1")

    return client.get_bag(space_id="digitised", source_id=b_number)


@functools.lru_cache()
def get_files(b_number):
    bag = get_bag(b_number)

    return {
        os.path.basename(f["name"]): {"size": f["size"], "checksum": f["checksum"]}
        for f in bag["manifest"]["files"]
        if f["name"].endswith(".xml")
    }


@functools.lru_cache()
def checksum(path):
    h = hashlib.sha256()
    h.update(open(path, "rb").read())
    return h.hexdigest()


@functools.lru_cache()
def size(path):
    return os.stat(path).st_size


def warn(s):
    print(termcolor.colored(s, "yellow"), file=sys.stderr)


def log_event(s):
    with open("alto_cleanup.log", "a") as out_file:
        out_file.write(s.rstrip() + "\n")


if __name__ == "__main__":
    root = "/Volumes/LIB_WDL_DDS/LIB_WDL_DDS_METS/"

    # Trying to look for the b number in an ALTO filename, e.g.
    #
    #     b21020000_0001.xml
    #
    B_NUMBER_RE = re.compile(r"^(?P<b_number>b[0-9]{7}[0-9x])")

    for alto_name, alto_path in tqdm.tqdm(get_alto_paths(root)):
        try:
            b_number = B_NUMBER_RE.match(alto_name).group("b_number")
        except AttributeError:
            warn(f"Unable to identify b number in {alto_path!r}")
            continue

        files = get_files(b_number)

        try:
            matching_file = files[alto_name]
        except KeyError:
            warn(f"Unable to find file in storage manifest for {alto_path!r}")
            continue

    
        if size(alto_path) != matching_file["size"]:
            warn(
                f"Sizes don't match:\nPath       = %s\nMETS share = %10d\nStorage    = %10d" %
                (alto_path, size(alto_path), matching_file["size"])
            )
            continue
        
        if checksum(alto_path) != matching_file["checksum"]:
            warn(
                f"Checksums don't match:\nPath       = %s\nMETS share = %s\nStorage    = %s\n" %
                (alto_path, checksum(alto_path), matching_file["checksum"])
            )
            continue
        
        log_event(f"Cleaning up: {alto_path}")

        # Uncomment the following line to actually run the deletions:
        # os.unlink(alto_path)
```

</details>

**Comment by alexwlchan** [comment]
Possibly related: #4200?

**Comment by pollecuttn** [comment]
Decommission on-prem Goobi environment
https://wellcomecloud.sharepoint.com/:w:/r/sites/wc2/DE/Platform/Shared%20Documents/AWS%20Goobi/Business%20Service%20Decommission%20Template.docx?d=wd8787912916645428f69358df1f7230b&csf=1&e=j6K1HA

**Comment by pollecuttn** [comment]
Info passed to Mark Gee who will put the decommission in motion.

**Comment by alexwlchan** [comment]
We've deleted as much as we can from LIB_WDL_DDS_METS (~5TB of stuff), and kept a backup copy of the METS in S3. I don't think we'll need it, but easier to put it there and leave it in Glacier for a few months until we think we want to inspect it in detail.

**Comment by alexwlchan** [comment]
We've "deleted" the S3 copy of the METS and ALTO files, but I think lifecycle rules on that bucket might be wonky (80M objects and issues with lifecycle rules, who knew)? Tracked here: https://github.com/wellcomecollection/platform/issues/4316

**Comment by alexwlchan** [comment]
(oops, wrong button)

**Comment by pollecuttn** [comment]
19 March 2020: Goobi servers switched off. Due for decommissioning 26 March 2020.

**Comment by pollecuttn** [comment]
CHG0030790 - Decommissioning of Preservica

**Comment by pollecuttn** [comment]
30 March 2020 Update from Chris for Goobi decommissioning: We have carried out all of the decommissioning except deleting the shares.

Deleting shares is expected to be completed by 31 March 2020 at the latest.

**Comment by pollecuttn** [comment]
3 April 2020 Update from Chris for Goobi decommissioning: Mesut had been pulled away from this work on a priority issue. He has advised it is taking quite some time to delete the data due to the number and size of the files.  He is continuing to delete the data and will let me know when this is completed.

**Comment by pollecuttn** [comment]
7 April update from Chris Luen: all the shares have been deleted except: 
•	Test Storage
o	\\wellcomeit.com\shares\LIB_WDL_WTS\LIB_WDL_WTS01

This is still in the process of being deleted.  I will let you know once Mesut has completed the last share.

**Comment by pollecuttn** [comment]
20 April 2020 update from Chris Luen:
I can confirm that the last share was completed over the weekend. 
Apologies for it taking so long.  There was just a lot of data and it had to be deleted in small amounts.

**Comment by pollecuttn** [comment]
28 April 2020: asked Chris Luen to decommission Preservica

**Comment by pollecuttn** [comment]
26 May 2020: confirmation from Chris Luen that Preservica servers have been decommissioned and deleted
