### ISSUE TITLE
Get ingests indexed in Elasticsearch

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4453]
- [x] Wire up the ingest indexer to write new ingests (https://github.com/wellcomecollection/platform/issues/4430)
- [x] Send all the existing ingests to the index (https://github.com/wellcomecollection/platform/issues/4431)
- [x] Set up rollup indexes for the ingests
- [x] Get accepted ingests to Elasticsearch (https://github.com/wellcomecollection/platform/issues/4429, https://github.com/wellcomecollection/platform/issues/4419)

**Comment by alexwlchan** [comment]
We're not going to do rollup jobs, so closing.
