### ISSUE TITLE
Put a tracker app in front of the bags database

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4534]
We should think about rearchitecting the bags service to have a single app in front of the database, same as we've done with the ingests service.

![bags_archiecture](https://user-images.githubusercontent.com/301220/82645786-5d2c9e80-9c0b-11ea-8384-a8c5e7d2d2fa.png)

- [x] Create the tracker stub (https://github.com/wellcomecollection/storage-service/pull/533)
- [x] Add a "list bag versions" endpoint (https://github.com/wellcomecollection/storage-service/pull/534)
- [x] Add a "get bag" endpoint (https://github.com/wellcomecollection/storage-service/pull/535)
- [x] Add a "get latest bag" endpoint
- [x] Modify the bags API to use the new endpoints
- [x] Modify the bag register to use the new endpoints
- [x] Modify the bag indexer to use the new endpoints

**Comment by alexwlchan** [comment]
Thought: I think the indexer should live outside the main task definition, because it's more of an "add-on" than the rest of the tasks. The reporting is a nice add-on to the storage service, but it should be possible to deploy without it.

**Comment by alexwlchan** [comment]
This would benefit https://github.com/wellcomecollection/platform/issues/4491

**Comment by alexwlchan** [comment]
I think this follows the same API as the external-facing bags API, with an additional `POST /bags` endpoint for creating new bags.

**Comment by alexwlchan** [comment]
Given we need this for the Glacier stuff, dropping the "discussion" tag – we do need to do this.
