### ISSUE TITLE
Fix the snapshot generator to enable IIIF rebuild

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4813]
We need to:
- Get the snapshot generator working again
- Ensure the snapshot generator will stay in sync with the Catalogue API
- Improve the long term operational reliability of snapshot generator

**TODO:**
- [x] Identify and provide data required for IIIF rebuild in snapshot #4815
- [x] Update snapshot_generator infrastructure #4816
- [x] Daily report on snapshot generator in Slack #4817

**Comment by jtweed** [comment]
Link to subfeature: https://wellcomecollection.productboard.com/feature-board/planning/features/5713542

**Comment by kenoir** [comment]
Consists of:

- [ ] https://github.com/wellcomecollection/platform/issues/4815
- [ ] https://github.com/wellcomecollection/platform/issues/4816
- [ ] https://github.com/wellcomecollection/platform/issues/4817
