### ISSUE TITLE
Process Archivematica packages that were blocked by the Miro migration

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4924]
Right now Archivematica is under pretty heavy load while we transfer all the Miro packages (#4881, #4882).

This ticket is to track all the Archivematica stuff that's blocked while we do that work:

- [x] #4919 Repackage and reinvest packages into Archivematica for Miten
- [x] #4921 Make sure Will's packages got through successfully
- [x] #4923 Remove the PP/ prefix from RefNos in the born-digital space
- [x] #4925 Don't upload bags to such a long path

**Comment by alexwlchan** [comment]
Done.
