### ISSUE TITLE
Redirect wellcomelibrary.org to wellcomecollection.org

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4977]

**Comment by jtweed** [comment]
Link to feature: https://wellcomecollection.productboard.com/feature-board/planning/features/4869604

**Comment by kenoir** [comment]
The library site has URLs like this:

- https://search.wellcomelibrary.org/iii/encore/record/C__Rb2475299
- https://wellcomelibrary.org/item/b2475299

**Comment by kenoir** [comment]
Looking around there are quite a few extant links to http://wellcomelibrary.org/collections/digital-collections/VALUE on the web - do we have a plan for mapping specific digital collections to somewhere else?

**Comment by kenoir** [comment]
Looking for "search.wellcomelibrary.org/iii/encore/search" also reveals there are references to URLs in the form:

- http://search.wellcomelibrary.org/iii/encore/search?target=erythromelalgia&submit=Search
- http://search.wellcomelibrary.org/iii/encore/search/C__Srosalind%20paget

These are both cut down examples, in reality these search URLS are full of crufty params that we probably don't care about.

**Comment by pollecuttn** [comment]
wellcomelibrary.org tab on https://wellcomecloud.sharepoint.com/:x:/s/wcdigitalexperience/EVeHngngpGVCl16B3AzCzcsBcTCMXYVGAp9x8tK9fWCK4Q?e=6ufmxM

**Comment by kenoir** [comment]
This isn't strictly on wellcomelibrary.org, but has the Library style - where do these URLs fit in the library site decommissioning process? e.g.

http://archives.wellcome.ac.uk/DServe/dserve.exe?dsqIni=Dserve.ini&dsqApp=Archive&dsqDb=Catalog&dsqCmd=show.tcl&dsqSearch=(RefNo==%27SABRO%2FA%27)

**Comment by kenoir** [comment]
Created some sub-issues for this:

- [ ] https://github.com/wellcomecollection/platform/issues/5059: Redirect Library Digitised Item URLs
- [ ] https://github.com/wellcomecollection/platform/issues/5056: Redirect Library Encore URLs
- [ ] https://github.com/wellcomecollection/platform/issues/5057: Redirect Library OPAC URLs
- [ ] https://github.com/wellcomecollection/platform/issues/5058: Redirect Library DServe URLs
- [ ] https://github.com/wellcomecollection/platform/issues/5060: Report on Library redirection stats

**Comment by jtweed** [comment]
Continued by #5405
