### ISSUE TITLE
Implement changes to the Location model

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5015]
Follows #4996; see [the proposed changes section of the RFC](https://github.com/wellcomecollection/docs/blob/master/rfcs/034-location_location_location/README.md)

- [x] Add the new AccessStatus types (#5011)
- [x] Add the new fields to Location (#5012)
- [x] Implement the new LocationType model (#5013)
- [x] Populate the new LocationType and shelfmark fields on Items from Sierra (#5014)
