### ISSUE TITLE
Mop up IIIF 3 creation - checklist - not C&D

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#5032]
Reuses list from https://github.com/wellcomecollection/storage-service/blob/0f367d8f8e751f239f4e9d63afc70e3fa1ea2624/bagger/reference_data/b_numbers.md#other-unwieldy-things

**b2178081x - 2 smallish volumes**
- [x] [test dash](https://iiif-test.wellcomecollection.org/dash/Manifestation/b2178081x)
- [x] [live dash](https://iiif.wellcomecollection.org/dash/Manifestation/b2178081x)
- [x] [live thumbs](http://tomcrane.github.io/wellcome-today/wc.org/3/thumbs.html?manifest=https://iiif.wellcomecollection.org/presentation/b2178081x)
- [x] [live manifest](https://iiif.wellcomecollection.org/presentation/b2178081x)
- [x] [wl.org+new](https://wellcomelibrary.org/item/b2178081x?wcorg=true) ([old](https://wellcomelibrary.org/item/b2178081x))
- [x] APPROVED

**b22454408 - short text - wl.org origin (other bucket)**
- [x] [test dash](https://iiif-test.wellcomecollection.org/dash/Manifestation/b22454408)
- [x] [live dash](https://iiif.wellcomecollection.org/dash/Manifestation/b22454408)
- [x] [live thumbs](http://tomcrane.github.io/wellcome-today/wc.org/3/thumbs.html?manifest=https://iiif.wellcomecollection.org/presentation/b22454408)
- [x] [live manifest](https://iiif.wellcomecollection.org/presentation/b22454408)
- [x] [wl.org+new](https://wellcomelibrary.org/item/b22454408?wcorg=true) ([old](https://wellcomelibrary.org/item/b22454408))
- [x] APPROVED

**b2043067x - 2 images no text**
- [x] [test dash](https://iiif-test.wellcomecollection.org/dash/Manifestation/b2043067x)
- [x] [live dash](https://iiif.wellcomecollection.org/dash/Manifestation/b2043067x)
- [x] [live thumbs](http://tomcrane.github.io/wellcome-today/wc.org/3/thumbs.html?manifest=https://iiif.wellcomecollection.org/presentation/b2043067x)
- [x] [live manifest](https://iiif.wellcomecollection.org/presentation/b2043067x)
- [x] [wl.org+new](https://wellcomelibrary.org/item/b2043067x?wcorg=true) ([old](https://wellcomelibrary.org/item/b2043067x))
- [x] APPROVED

**b24923333 - 2 x 550 page MM**
- [x] [test dash](https://iiif-test.wellcomecollection.org/dash/Manifestation/b24923333)
- [x] [live dash](https://iiif.wellcomecollection.org/dash/Manifestation/b24923333)
- [x] [live thumbs](http://tomcrane.github.io/wellcome-today/wc.org/3/thumbs.html?manifest=https://iiif.wellcomecollection.org/presentation/b24923333)
- [x] [live manifest](https://iiif.wellcomecollection.org/presentation/b24923333)
- [x] [wl.org+new](https://wellcomelibrary.org/item/b24923333?wcorg=true) ([old](https://wellcomelibrary.org/item/b24923333))
- [x] APPROVED

**b30136155 - short MOH report**
- [x] [test dash](https://iiif-test.wellcomecollection.org/dash/Manifestation/b30136155)
- [x] [live dash](https://iiif.wellcomecollection.org/dash/Manifestation/b30136155)
- [x] [live thumbs](http://tomcrane.github.io/wellcome-today/wc.org/3/thumbs.html?manifest=https://iiif.wellcomecollection.org/presentation/b30136155)
- [x] [live manifest](https://iiif.wellcomecollection.org/presentation/b30136155)
- [x] [wl.org+new](https://wellcomelibrary.org/item/b30136155?wcorg=true) ([old](https://wellcomelibrary.org/item/b30136155))
- [x] APPROVED

**b16641097 - Video, no transcript**
- [x] [test dash](https://iiif-test.wellcomecollection.org/dash/Manifestation/b16641097)
- [x] [live dash](https://iiif.wellcomecollection.org/dash/Manifestation/b16641097)
- [x] [live thumbs](http://tomcrane.github.io/wellcome-today/wc.org/3/thumbs.html?manifest=https://iiif.wellcomecollection.org/presentation/b16641097)
- [x] [live manifest](https://iiif.wellcomecollection.org/presentation/b16641097)
- [x] [wl.org+new](https://wellcomelibrary.org/item/b16641097?wcorg=true) ([old](https://wellcomelibrary.org/item/b16641097))
- [x] APPROVED

**b16759230 - Video, expressed as multiple manifestation, but only one manifestation present**
- [x] [test dash](https://iiif-test.wellcomecollection.org/dash/Manifestation/b16759230)
- [x] [live dash](https://iiif.wellcomecollection.org/dash/Manifestation/b16759230)
- [x] [live thumbs](http://tomcrane.github.io/wellcome-today/wc.org/3/thumbs.html?manifest=https://iiif.wellcomecollection.org/presentation/b16759230)
- [x] [live manifest](https://iiif.wellcomecollection.org/presentation/b16759230)
- [x] [wl.org+new](https://wellcomelibrary.org/item/b16759230?wcorg=true) ([old](https://wellcomelibrary.org/item/b16759230))
- [x] APPROVED

**b16675630 - Video, with transcript (2-part multiple manifestation)**
- [x] [test dash](https://iiif-test.wellcomecollection.org/dash/Manifestation/b16675630)
- [ ] [live dash](https://iiif.wellcomecollection.org/dash/Manifestation/b16675630)
- [ ] [live thumbs](http://tomcrane.github.io/wellcome-today/wc.org/3/thumbs.html?manifest=https://iiif.wellcomecollection.org/presentation/b16675630)
- [x] [live manifest](https://iiif.wellcomecollection.org/presentation/b16675630)
- [x] [wl.org+new](https://wellcomelibrary.org/item/b16675630?wcorg=true) ([old](https://wellcomelibrary.org/item/b16675630))
- [ ] APPROVED

**b28462270 - PDF only (born digital but currently in same workflow)**
- [x] [test dash](https://iiif-test.wellcomecollection.org/dash/Manifestation/b28462270)
- [x] [live dash](https://iiif.wellcomecollection.org/dash/Manifestation/b28462270)
- [x] [live thumbs](http://tomcrane.github.io/wellcome-today/wc.org/3/thumbs.html?manifest=https://iiif.wellcomecollection.org/presentation/b28462270)
- [x] [live manifest](https://iiif.wellcomecollection.org/presentation/b28462270)
- [x] [wl.org+new](https://wellcomelibrary.org/item/b28462270?wcorg=true) ([old](https://wellcomelibrary.org/item/b28462270))
- [x] APPROVED

**b17307922 - Audio, MP3**
- [x] [test dash](https://iiif-test.wellcomecollection.org/dash/Manifestation/b17307922)
- [x] [live dash](https://iiif.wellcomecollection.org/dash/Manifestation/b17307922)
- [x] [live thumbs](http://tomcrane.github.io/wellcome-today/wc.org/3/thumbs.html?manifest=https://iiif.wellcomecollection.org/presentation/b17307922)
- [x] [live manifest](https://iiif.wellcomecollection.org/presentation/b17307922)
- [x] [wl.org+new](https://wellcomelibrary.org/item/b17307922?wcorg=true) ([old](https://wellcomelibrary.org/item/b17307922))
- [x] APPROVED

**b29524404 - Audio Multiple Manifestation (interview with PDF transcript)**
- [ ] [test dash](https://iiif-test.wellcomecollection.org/dash/Manifestation/b29524404)
- [ ] [live dash](https://iiif.wellcomecollection.org/dash/Manifestation/b29524404)
- [x] [live thumbs](http://tomcrane.github.io/wellcome-today/wc.org/3/thumbs.html?manifest=https://iiif.wellcomecollection.org/presentation/b29524404)
- [x] [live manifest](https://iiif.wellcomecollection.org/presentation/b29524404)
- [ ] [wl.org+new](https://wellcomelibrary.org/item/b29524404?wcorg=true) ([old](https://wellcomelibrary.org/item/b29524404))
- [ ] APPROVED

**b20641151 - A very large archive (5661 images) without access control**
- [ ] [test dash](https://iiif-test.wellcomecollection.org/dash/Manifestation/b20641151)
- [ ] [live dash](https://iiif.wellcomecollection.org/dash/Manifestation/b20641151)
- [x] [live thumbs](http://tomcrane.github.io/wellcome-today/wc.org/3/thumbs.html?manifest=https://iiif.wellcomecollection.org/presentation/b20641151)
- [x] [live manifest](https://iiif.wellcomecollection.org/presentation/b20641151)
- [x] [wl.org+new](https://wellcomelibrary.org/item/b20641151?wcorg=true) ([old](https://wellcomelibrary.org/item/b20641151))
- [x] APPROVED

**b24963215 - A very large archive (6320 images) with access control**
- [ ] [test dash](https://iiif-test.wellcomecollection.org/dash/Manifestation/b24963215)
- [ ] [live dash](https://iiif.wellcomecollection.org/dash/Manifestation/b24963215)
- [x] [live thumbs](http://tomcrane.github.io/wellcome-today/wc.org/3/thumbs.html?manifest=https://iiif.wellcomecollection.org/presentation/b24963215)
- [x] [live manifest](https://iiif.wellcomecollection.org/presentation/b24963215)
- [x] [wl.org+new](https://wellcomelibrary.org/item/b24963215?wcorg=true) ([old](https://wellcomelibrary.org/item/b24963215))
- [x] APPROVED

**b24990796 - A work with a very large number of volumes (66 manifestations, 10,136 images)**
- [ ] [test dash](https://iiif-test.wellcomecollection.org/dash/Manifestation/b24990796)
- [x] [live dash](https://iiif.wellcomecollection.org/dash/Manifestation/b24990796)
- [x] [live thumbs](http://tomcrane.github.io/wellcome-today/wc.org/3/thumbs.html?manifest=https://iiif.wellcomecollection.org/presentation/b24990796)
- [x] [live manifest](https://iiif.wellcomecollection.org/presentation/b24990796)
- [x] [wl.org+new](https://wellcomelibrary.org/item/b24990796?wcorg=true) ([old](https://wellcomelibrary.org/item/b24990796))
- [x] APPROVED

**b29236927 - A 6 "volume" audio multiple manifestation (does not work in Library UV)**
- [ ] [test dash](https://iiif-test.wellcomecollection.org/dash/Manifestation/b29236927)
- [ ] [live dash](https://iiif.wellcomecollection.org/dash/Manifestation/b29236927)
- [ ] [live thumbs](http://tomcrane.github.io/wellcome-today/wc.org/3/thumbs.html?manifest=https://iiif.wellcomecollection.org/presentation/b29236927)
- [ ] [live manifest](https://iiif.wellcomecollection.org/presentation/b29236927)
- [ ] [wl.org+new](https://wellcomelibrary.org/item/b29236927?wcorg=true) ([old](https://wellcomelibrary.org/item/b29236927))
- [x] APPROVED

**b20298341 - Arabic manuscript, mixed languages**
- [x] [test dash](https://iiif-test.wellcomecollection.org/dash/Manifestation/b20298341)
- [x] [live dash](https://iiif.wellcomecollection.org/dash/Manifestation/b20298341)
- [x] [live thumbs](http://tomcrane.github.io/wellcome-today/wc.org/3/thumbs.html?manifest=https://iiif.wellcomecollection.org/presentation/b20298341)
- [x] [live manifest](https://iiif.wellcomecollection.org/presentation/b20298341)
- [x] [wl.org+new](https://wellcomelibrary.org/item/b20298341?wcorg=true) ([old](https://wellcomelibrary.org/item/b20298341))
- [x] APPROVED

**b19291449 - Manuscript with structure (TOC)**
- [x] [test dash](https://iiif-test.wellcomecollection.org/dash/Manifestation/b19291449)
- [x] [live dash](https://iiif.wellcomecollection.org/dash/Manifestation/b19291449)
- [x] [live thumbs](http://tomcrane.github.io/wellcome-today/wc.org/3/thumbs.html?manifest=https://iiif.wellcomecollection.org/presentation/b19291449)
- [x] [live manifest](https://iiif.wellcomecollection.org/presentation/b19291449)
- [x] [wl.org+new](https://wellcomelibrary.org/item/b19291449?wcorg=true) ([old](https://wellcomelibrary.org/item/b19291449))
- [x] APPROVED

**b19192162 - Clickthrough**
- [x] [test dash](https://iiif-test.wellcomecollection.org/dash/Manifestation/b19192162)
- [x] [live dash](https://iiif.wellcomecollection.org/dash/Manifestation/b19192162)
- [x] [live thumbs](http://tomcrane.github.io/wellcome-today/wc.org/3/thumbs.html?manifest=https://iiif.wellcomecollection.org/presentation/b19192162)
- [x] [live manifest](https://iiif.wellcomecollection.org/presentation/b19192162)
- [x] [wl.org+new](https://wellcomelibrary.org/item/b19192162?wcorg=true) ([old](https://wellcomelibrary.org/item/b19192162))
- [x] APPROVED

**b19974760 - Chemist and Druggist!**
- [ ] [test dash](https://iiif-test.wellcomecollection.org/dash/Manifestation/b19974760)
- [ ] [live dash](https://iiif.wellcomecollection.org/dash/Manifestation/b19974760)
- [ ] [live thumbs](http://tomcrane.github.io/wellcome-today/wc.org/3/thumbs.html?manifest=https://iiif.wellcomecollection.org/presentation/b19974760)
- [ ] [live manifest](https://iiif.wellcomecollection.org/presentation/b19974760)
- [ ] [wl.org+new](https://wellcomelibrary.org/item/b19974760?wcorg=true) ([old](https://wellcomelibrary.org/item/b19974760))
- [ ] APPROVED

**Comment by aray-wellcome** [comment]
@tomcrane I've gone through this list and viewed the items with the IIIF source toggle on. 

These are the issues I found. 

**b24923333** - It works but volume 2 is showing as Vol 180702. This is showing in the METS so probably a bad harvest from IA rather than IIIF Builder's problem.  I'll put it on the fix list. I've marked it APPROVED. 

**b16675630** - seems to be missing its poster image. I can see it in the bag though. 

**b29524404** - can't find the PDF transcript link on the page

**b20641151** & **b24963215** - still can't load these in the dash but looks fine on WC and in the thumbs viewer. Not a blocker though so marked as APPROVED. 

**b29236927** - a test for MM audio from 2019. Not a blocker that it doesn't work on WC. Can delete and ingest again when we address the new audio workflow. Marked APPROVED because it's not IIIF builder's problem it doesn't work.

**Comment by tomcrane** [comment]
**b16675630** is addressed by https://github.com/wellcomecollection/iiif-builder/pull/166, will be deployed in a moment.

**b29524404** might be a question for @gestchild 

With the toggle on, I can see that this one has its transcript, in the right place. This is b16803668:
https://wellcomecollection.org/works/mswhef45

However b29524404 does not show a link to the transcript on the page. I can think of two reasons for this.

* The item ID has spaces in it. This is something we need to address soon, see https://github.com/wellcomecollection/docs/pull/30
This might not be the reason though, because the MP3 has the same fragility, and that plays fine.

* The template for an archive item doesn't have a place for this link.

**Comment by tomcrane** [comment]
Closing, as there are no remaining blockers.
I will tweak my thumbs viewer to allow you to test C&D search and structure.
