### ISSUE TITLE
Checklist: API Paths under iiif.wellcomecollection.org

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#5039]
(successor to https://github.com/wellcomecollection/platform/issues/4659)

## API Paths under iiif.wellcomecollection.org 

Work in progress, need to update this checklist with final paths.

(`/text` is under api.wellcomecollection.org but still served by same app, so either work, up to ALB rules)

### Manifests and Collections that are digitised items (can be related to _one_ work)

They all support conneg
Will return Presentation 3 resources by default

- [x] `/presentation/b28047345` (Manifest; single volume work)
- [x] `/presentation/b18031511_0003` (Manifest; volume from a multiple volume work)
- [x] `/presentation/b18031511` (Collection; the multiple volume work)
- [x] `/presentation/b19974760` (Collection; C&D)
- [x] `/presentation/b19974760_0040` (Collection; C&D Volume)
- [x] `/presentation/b19974760_0040_0003` (Manifest; C&D Issue)

Explicit paths are also available - v2 = Presentation 2.1, v3 = Presentation 3.0 (for now).

- [x] `/presentation/v2/b18031511`
- [x] `/presentation/v3/b18031511` 

### Collections that are sets of different digitised items (e.g., by subject)

(Also support conneg, and explicit paths)

- [x] `/presentation/collections`
- [x] `/presentation/collections/subjects`
- [x] `/presentation/collections/subjects/sk5n9ffw` (Elizabeth I)
- [x] `/presentation/collections/genres/Oil%20paintings` (no identifier...)

### Search API

v1 and v2 placeholder. v2 _could_ just return v1, but we'll do a little tidying up.
NB v1 is the version of the search service, not the Presentation API

- [x] `/search/v1/b28047345`
- [x] `/autocomplete/v1/b28047345`
- [x] `/search/v2/b28047345`
- [x] `/autocomplete/v2/b28047345`

### Text 

(nb will be at api.wellcomecollection.org)
No conneg here. The `/v1/` is Wellcome Collection API version (see #4603)

- [x] `/text/v1/b28047345` (single volume)
- [x] `/text/v1/b18031511_0003` (single volume of multiple volume work)
- [x] `/text-zip/v1/b18031511` (? zip file of texts for all volumes - see https://wellcomelibrary.org/service/fulltextzip/b18031511)

### Canvas identity

Some operations are for a single canvas (in practice, related to a single JP2 or video).
E.g., the text of a single page in Annotation or ALTO form.

We also need Canvas identity in Manifests, whether or not we want to make them dereferenceable.

In v2 and v3 manifests, the Canvas identity must be the same canonical form, as it is the target of annotations. But where do we get the identifier from? We are abandoning DDS-inferred index-based IDs in favour of information from METS, which is a better source of truth.

Candidates are:

* `/canvas/b18031511_0003/PHYS_0179`
* `/canvas/b18031511_0003/b18031511_0003_0181.jp2`
* `/canvas/b18031511_0003_0181.jp2`

The first is more aesthetically appealing and doesn't confusingly end in an image file extension.
The second and third are consistent with the DLCS identifier, which is more practical for consumers and spelunkers (you can cut and paste a bit of this identifier to a DLCS image service).

The second has some redundancy, as we already guarantee global uniqueness of the filename-derived identifier (see RFC). On the other hand, the second allows operations like `/annotations/...` to have manifest AND canvas level actions.

I think my preference is for 

- [x] `/canvas/b18031511_0003/b18031511_0003_0181.jp2`

This form is used in the following examples.

### Annotations

These don't need conneg, we won't do that for now but could put it in later. The already-negotiated manifest links to explicit paths for further linked resources, because you have already made a version decision.

As there is an absolute mapping between IIIF version and Anno model, we should use the Presentation API versions, same as Manifests, to distinguish between Open Annotation and W3C Web Anno Data Model.

We should also include a slot in the path for text granularity, even if we only provide `line` level (as now) - https://iiif.io/api/extension/text-granularity/#2-text-granularity-levels-and-the-textgranularity-property 

(Offering other levels in future is trivially easy, we just don't do it right now. Apart from `glyph`, for which we don't have the OCR data).

### Manifest level

We have two manifest level annotation pages.

- [x] `/annotations/v2/line/b18031511_0003/all`
- [x] `/annotations/v2/line/b18031511_0003/images` (just the figure/picture/table bounding boxes)

This does mean that `all` and `images` are magic strings as they occupy the same slot as the Canvas ID in the following:

### Annotations for one page

(v2 and v3 are _Presentation API_ versions; map to OA and W3C)

- [x] `/annotations/v2/line/b18031511_0003/b18031511_0003_0181.jp2` - returns Open Annotation 
- [x] `/annotations/v3/line/b18031511_0003/b18031511_0003_0181.jp2` - returns W3C Annos

### METS-ALTO

Versioning is hard here. What exactly are you specifying? METS-ALTO versioning varies over time depending on when something was digitised and who did it.

- [x] `/text/alto/b18031511_0003/b18031511_0003_0181.jp2`

### Poster Image (not DLCS)

- [x] `/thumbs/b28047345`
- [x] `/thumbs/b18031511_0003`

### Work-level thumbnail

https://wellcomelibrary.org/service/workthumb/b18310916/0
This is not needed as wc.org will have better logic for this. (?)

### Repository Logo

- [x] `/repository/b24967646`

Current: https://wellcomelibrary.org/biblio/b24967646/repositoryLogo
NB get the text to match from noteType: `{id: "location-of-original"...}`

### PDF Cover Page 

(not the full PDF which comes from DLCS)

- [x] `/pdf-cover/b18031511_0003` 

(NB this is the Manifest level ID, not the collection; this allows variant cover pages for volumes of a multi-volume work)
current: https://wellcomelibrary.org/service/pdfcoverpageaspdf/b18310916

(aside) Consider making this a Python service or even a Lambda that gets what it needs from the Manifest in S3.
There are better PDF libraries available in Python than .NET Core - existing .NET libraries often make Win32 calls that won't work on Linux. Everything it needs should be in the Manifest (this is a good exercise for considering what goes in the `provider` Presentation 3 structure).

### MOH

(MOH API omitted from here for now)

_*Other stuff that isn't so public, that we can just port with sensible options*_

### Semi-internal API (used in dashboard and testing tools)

- [x] `/service/suggest-b-number`

https://wellcomelibrary.org/service/bNumberSuggestion?q=john%20dee
https://wellcomelibrary.org/service/bNumberSuggestion?q=b14658

### Used by UV

https://wellcomelibrary.org/service/playerconfig
https://wellcomelibrary.org/service/playerconfig?v=moh
(also licenses and options config)

### FileInfo

There are many endpoints used by the dashboard for instrumentation on caches that are redundant now, I won't list them here.

### Healthchecks (used by Pingdom, and then Wellcome monitoring, and our own monitoring)

Example: https://wellcomelibrary.org/service/DdsHealthCheck.Release1

### Existing API that isn't used any more

https://wellcomelibrary.org/biblio/b14658161
https://wellcomelibrary.org/service/snippet/b28047345/0?snippetSize=100&intList=5005 
https://wellcomelibrary.org/service/imagelist/b28047345/0

Was consumed by Encore full text harvester:
https://wellcomelibrary.org/service/BornDigitalBibs?from=2020-01-01
https://wellcomelibrary.org/service/AltoBibs?from=2020-06-01&to=2020-06-30
