### ISSUE TITLE
Checklist: population of new DDS

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#5040]
Replaces #4752

For all Manifests and Collections:

 - [x] Do they pass the IIIF Validator? 
 - [x] Do they work in Mirador? 
 - [x] Do they work in the UV?
 - [x] Other viewers? TIFY perhaps.
 - [x] Do the IIIF 2 versions work on the wl.org item pages? 
 - [x] Do the IIIF 2 versions work on wc.org works pages?

At the moment:

- iiif.wc.org uses prod preservation storage and prod DLCS space (space 5)
- iiif-test.wc.org uses prod preservation storage and stage DLCS space (space 6)
- iiif-stage.wc.org uses stage preservation storage and stage DLCS space (space 6).

For the full content creation run, we don't want to do any DLCS synchronisation (DLCS already has the images in space 5). Control of this is covered in https://github.com/wellcomecollection/iiif-builder/pull/78.

For limited test runs (e.g., 10% of the content), if we do that on iiif-test, then we'll do a huge amount of unnecessary DLCS image registration (as space 6 doesn't have the images).

We could either make iiif-test use space 5 for this kind of work, or run them into iiif.wc.org (production). We can clear it out multiple times. This latter option seems cleaner and keeps the test environment for other kinds of testing, but it might look more official than desired - are these real Wellcome manifests? Does that matter?

Once we are happy with this we need to roll the presses - generate the ~3-400K IIIF resources (x 2) and the ~30m annotation pages (x 1). This is a massively parallelisable process.

- [x] Decide how we want to parallelise WorkflowProcessor to take jobs - fargate?
- [x] Decide how we want to populate the initial WorkflowJobs (have a temporary EC2 to run these tasks from?)
- [x] Add some instrumentation to the Dashboard GoobiCall UI so we can track progress of the workflow jobs
- [x] Some small test runs of the above
- [x] Unleash the Kraken

**Comment by tomcrane** [comment]
All ticked!
