### ISSUE TITLE
Move Catalogue Pipeline services from ECS to Lambda

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#5784]
In order to reduce infrastructure and application complexity we should move pipeline services from auto-scaling ECS services. This will allow us to move scaling and batching log out of application and infrastructure code, and into hosted services with simpler configuration options.

This will involve:
- [ ] Writing an RFC to describe the approach and reasoning in more detail
- [ ] Writing an ADR to summarise the specifics of the architecture change
- [ ] Migrate identified services in a phased manner

**Comment by kenoir** [comment]
In Q1 2024/25 we may want to deal with the following services:

- Batcher: to deal with necessary batching logic
- Sierra Transformer: to deal with operating at scale
- ID Minter: to deal with handling database connections and limiting scale

**Comment by jcateswellcome** [comment]
@kenoir I've closed a bunch of other epics because I think the milestone tracking, labels and parent/child features on Github projects are mature enough to make these separate tickets a bit redundant now. However, this epic is probably still in play so I will likely leave it for now.
