### ISSUE TITLE
Review potential future Library & Collections Management systems from an integration perspective

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#5786]
> [!Note]
> See this [Notion Epic](https://www.notion.so/wellcometrust/Future-collections-management-systems-scoping-80a72d2d6afd4995932ff8ea00cc468b?pvs=4).

In order to prepare for the Wellcome Collection Systems Transformation project we should review candidate systems with a view to how we would handle catalogue-pipeline integration with that supplier.

Initially we will be looking at the Collections Management Systems which for the most part replace the functionality offered by CALM:

The 4 suppliers we will review are:
- [x] https://github.com/wellcomecollection/platform/issues/5797
- [x] https://github.com/wellcomecollection/platform/issues/5799
- [x] https://github.com/wellcomecollection/platform/issues/5800
- [x] https://github.com/wellcomecollection/platform/issues/5798

The outcome for each will be documentation in the /docs repository discussing potential integration supplier.

**Comment by jcateswellcome** [comment]
Updated with the 4 we will review this quarter and in light of initial focus on collections management systems
