### ISSUE TITLE
Build Library Data Link Explorer

### ISSUE THREAD

**Issue by georgiaewhitney** [wellcomecollection/platform#5826]
Develop a web application (currently titled Library Data Link Explorer) that replicates the functionality of the matcher script in the [catalogue-pipeline](https://github.com/wellcomecollection/catalogue-pipeline) but makes it accessible to CI staff. The app will allow staff who need to explore the relationships between library records input a work`id` and return a visual graph representation (not dissimilar to the pdf) of that work's relationships using nodes and edges. 

By integrating with Elasticsearch and visualising graphs on the frontend, the app eliminates the need for individuals to require AWS permissions or running scripts manually, providing CI staff with an intuitive way to explore and debug relationships between records.

[wip]

## Subtasks
- [x] Write up RFC for project context
- [x] Set up data-link repo
- [x] Set up the API to retrieve data from Elasticsearch using `matcher-graph` logic
- [x] Build the frontend to display the graph using a selected library (e.g., Sigma.js or Graphviz).
- [x] Deploy App
- [x] Write unit tests for the API and frontend.
- [x] Conduct end-to-end testing with CI staff.
- [x] Consider Security protocols
